# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esteticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('horario', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('lat', models.CharField(max_length=20)),
                ('log', models.CharField(max_length=20)),
                ('img_logo', models.CharField(max_length=200)),
                ('img_banner', models.CharField(max_length=200)),
                ('img1', models.CharField(max_length=200)),
                ('img2', models.CharField(max_length=200)),
                ('img3', models.CharField(max_length=200)),
                ('img4', models.CharField(max_length=200)),
                ('img5', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('horario', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('lat', models.CharField(max_length=20)),
                ('log', models.CharField(max_length=20)),
                ('img_logo', models.CharField(max_length=200)),
                ('img_banner', models.CharField(max_length=200)),
                ('img1', models.CharField(max_length=200)),
                ('img2', models.CharField(max_length=200)),
                ('img3', models.CharField(max_length=200)),
                ('img4', models.CharField(max_length=200)),
                ('img5', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Veterinarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('horario', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('lat', models.CharField(max_length=20)),
                ('log', models.CharField(max_length=20)),
                ('img_logo', models.CharField(max_length=200)),
                ('img_banner', models.CharField(max_length=200)),
                ('img1', models.CharField(max_length=200)),
                ('img2', models.CharField(max_length=200)),
                ('img3', models.CharField(max_length=200)),
                ('img4', models.CharField(max_length=200)),
                ('img5', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
